#ifndef UI_MACROS_H
#define UI_MACROS_H

#define CELL_ID_WIDTH 120
#define CELL_NAME_WIDTH 160
#define CELL_TYPE_WIDTH 140
#define CELL_VENDOR_WIDTH 140
#define CELL_MODEL_WIDTH 160
#define CELL_IP_ADDRESS_WIDTH 150
#define CELL_MAC_ADDRESS_WIDTH 170
#define CELL_LOCATION_WIDTH 180
#define CELL_STATUS_WIDTH 160
#define CELL_LAST_CHECK_WIDTH 160

#endif
