#ifndef UI_MACROS_H
#define UI_MACROS_H

#define CELL_ID_WIDTH 100
#define CELL_CODE_WIDTH 100
#define CELL_NUMBER_WIDTH 100 
#define CELL_NAME_WIDTH 160
#define CELL_TYPE_WIDTH 140
#define CELL_VALUE_WIDTH 140 
#define CELL_VENDOR_WIDTH 140
#define CELL_MODEL_WIDTH 160
#define CELL_IP_ADDRESS_WIDTH 140
#define CELL_MAC_ADDRESS_WIDTH 170
#define CELL_LOCATION_WIDTH 180
#define CELL_STATUS_WIDTH 160
#define CELL_LAST_CHECK_WIDTH 160
#define CELL_QUEUE_WIDTH 80
#define CELL_SOURCE_WIDTH 160
#define CELL_DESCRIPTION_WIDTH 250
#define CELL_PRIORITY_WIDTH 140 
#define CELL_TECHNICIAN_WIDTH 160 
#define CELL_CREATED_WIDTH 160 
#define CELL_CONCLUDED_WIDTH 160
#define CELL_READ_AT_WIDTH 160

#endif
